### ISSUE TITLE
zpa_talker needs a method to list application segments

### ISSUE THREAD

**Issue by zetan503** [sergitopereira/zscaler_api_talkers#34]
list_application_segments expects an application ID, but you don't provide a method to discover all the app IDs.

  # application-controller
    def list_application_segments(self, applicationId=None):
        """
        Method to obtain application segments
        :param applicationId type int. Application unique identified id
        """
        if applicationId:
            url = f'/mgmtconfig/v1/admin/customers/{self.customerId}/application/{applicationId}'
            response = self.hp_http.get_call(url, headers=self.header, error_handling=True)
            return response.json()
        url = f'/mgmtconfig/v1/admin/customers/{self.customerId}/application'
        response = self._obtain_all_results(url)
        return 

Instead make list_application_segments return a list of all applications
url = f"https://config.private.zscaler.com/mgmtconfig/v1/admin/customers/{customer_id}/application"

And then add a new method get_application_segment(appid)
to get the app details
   url = f'/mgmtconfig/v1/admin/customers/{self.customerId}/application/{applicationId}'

**Comment by sergitopereira** [comment]
@zetan503 the applicationid is optional and by default set to NONE. If value not passed, the method will list all applications

**Comment by zetan503** [comment]
Perfect, that worked. Thank you for the quick support!
