### ISSUE TITLE
Help with add_policySet and getting the global policy id

### ISSUE THREAD

**Issue by zetan503** [sergitopereira/zscaler_api_talkers#38]
While attempting to use add_policySet I see that policySetId needs to be the global policy ID.
The method says
        :param policySetId:  Global Policy ID. can be obtained from list_global_policy_id

Calling  list_global_policy_id() results in object not found

DEBUG:urllib3.connectionpool:https://config.private.zscaler.com:443 "GET /mgmtconfig/v1/admin/customers/XXXXXXXXXXXXX/policySet/global?pagesize=500 HTTP/1.1" 404 None
Resource does not exist

Passing
list_global_policy_id("GLOBAL_POLICY") results in
DEBUG:urllib3.connectionpool:https://config.private.zscaler.com:443 "GET /mgmtconfig/v1/admin/customers/XXXXXXXXXXXXX/policySet/globalGLOBAL_POLICY HTTP/1.1" 404 None
Resource does not exist

Looking at the API docs, I see I can query policySet/policyType/GLOBAL_POLICY and get the global policy id.
Should the list_global_policy_id() method in zpa_talker.py use this call instead?

https://config.private.zscaler.com/mgmtconfig/v1/admin/customers/XXXXXXXXXXXXX/policySet/policyType/GLOBAL_POLICY
{'id': '288257894007177221', 'modifiedTime': '1679082570', 'creationTime': '1655150912', 'modifiedBy': '288257894007177501', 'name': 'Global_Policy', 'enabled': True, 'description': 'The rules in this policy set are executed first.', 'policyType': '1', 'sorted': True}

**Comment by sergitopereira** [comment]
Thank you @zetan503 for raising this bug. The endpoint has been deprecated. I just pushed the fixed and package will be released by end of today.  New Method  zpa.list_policySet()
Regards
Sergio

**Comment by sergitopereira** [comment]
@zetan503  Please update to zscaler-api-talkers 4.0.2.  Replaced legacy api call with list_policySet method 

zpa.list_policySet()
{'id': '12343241541',
 'modifiedTime': '1675889349',
 'creationTime': '1616692393',
 'modifiedBy': '216195906217706050',
 'name': 'Global_Policy',
 'enabled': True,
 'description': 'The rules in this policy set are executed first.',
 'policyType': '1',
 'sorted': True}

**Comment by zetan503** [comment]
I think you need to update the comments to reflect that change

401 def add_policySet
412        :param policySetId:  Global Policy ID. can be obtained from list_global_policy_id

**Comment by sergitopereira** [comment]
@zetan503 thanks. will do on next release! great catch
