### ISSUE TITLE
list_policySet enum confusion

### ISSUE THREAD

**Issue by zetan503** [sergitopereira/zscaler_api_talkers#42]
Playing with the new list_policySet function, I tried all the types

  for type in [
        "ACCESS_POLICY",
        "GLOBAL_POLICY",
        "TIMEOUT_POLICY",
        "REAUTH_POLICY",
        "SIEM_POLICY",
        "CLIENT_FORWARDING_POLICY",
        "BYPASS_POLICY",
    ]:
        print(type)
        print(client.list_policySet(policyType=type))

What I found when I query each type is some of them point to the same object id / type, but it looks like the type and the name are mismatched. Is this a misconfiguration in our zpa tenant?

Query for ACCESS_POLICY or GLOBAL_POLICY returns the same id
Query for TIMEOUT_POLICY or REAUTH_POLICY returns the same id
Query for CLIENT_FORWARDING_POLICY or BYPASS_POLICY returns the same id

```

ACCESS_POLICY
{'id': '288257894007177221', 'modifiedTime': '1679082570', 'creationTime': '1655150912', 'modifiedBy': '288257894007177501', 'name': 'Global_Policy', 'enabled': True, 'description': 'The rules in this policy set are executed first.', 'policyType': '1', 'sorted': True}

GLOBAL_POLICY
{'id': '288257894007177221', 'modifiedTime': '1679082570', 'creationTime': '1655150912', 'modifiedBy': '288257894007177501', 'name': 'Global_Policy', 'enabled': True, 'description': 'The rules in this policy set are executed first.', 'policyType': '1', 'sorted': True}

TIMEOUT_POLICY
{'id': '288257894007177222', 'modifiedTime': '1668536066', 'creationTime': '1655150912', 'modifiedBy': '288257894007177503', 'name': 'ReAuth_Policy', 'enabled': True, 'description': 'Re-Authentication policies.', 'policyType': '2', 'sorted': True}

REAUTH_POLICY
{'id': '288257894007177222', 'modifiedTime': '1668536066', 'creationTime': '1655150912', 'modifiedBy': '288257894007177503', 'name': 'ReAuth_Policy', 'enabled': True, 'description': 'Re-Authentication policies.', 'policyType': '2', 'sorted': True}

SIEM_POLICY
{'id': '288257894007177266', 'modifiedTime': '1661445486', 'creationTime': '1656352415', 'modifiedBy': '288257894007177233', 'name': 'Siem_Policy', 'enabled': True, 'description': 'Siem policies.', 'policyType': '3', 'sorted': True}

CLIENT_FORWARDING_POLICY
{'id': '288257894007177225', 'modifiedTime': '1677098461', 'creationTime': '1655150912', 'modifiedBy': '288257894007177502', 'name': 'Bypass_Policy', 'enabled': True, 'description': 'Bypass policies.', 'policyType': '4', 'sorted': True}

BYPASS_POLICY
{'id': '288257894007177225', 'modifiedTime': '1677098461', 'creationTime': '1655150912', 'modifiedBy': '288257894007177502', 'name': 'Bypass_Policy', 'enabled': True, 'description': 'Bypass policies.', 'policyType': '4', 'sorted': True}

```

**Comment by sergitopereira** [comment]
@zetan503  this is expected as per https://help.zscaler.com/zpa/policy-set-controller#/mgmtconfig/v1/admin/customers/{customerId}/policySet/{policySetId}/rule-post

policyType *required
string
(path)
Type for differentiating policy types. Supported values: ACCESS_POLICY/GLOBAL_POLICY, TIMEOUT_POLICY/REAUTH_POLICY, SIEM_POLICY, CLIENT_FORWARDING_POLICY/BYPASS_POLICY, INSPECTION_POLICY
