### ISSUE TITLE
ZPA create_application_segment serverGroup syntax

### ISSUE THREAD

**Issue by zetan503** [sergitopereira/zscaler_api_talkers#44]
The API for add_application_segment says
  :param serverGroups=type list. list of dictionaries, where key is id and value is serverGroupId [{
                "id": "<serverGroupId>"}]

send: b'{"name": "APP_TEST_ALLUSERS", "description": "", "enabled": true, "healthCheckType": "DEFAULT", "healthReporting": "NONE", "icmpAccessType": "NONE", "ipAnchored": false, "doubleEncrypt": false, "bypassType": "NEVER", "isCnameEnabled": true, "clientlessApps": [], "inspectionApps": [], "sraApps": [], "commonAppsDto": {}, "selectConnectorCloseToApp": false, "passiveHealthEnabled": true, "tcpPortRanges": [22, 443], "tcpPortRange": [], "udpPortRange": [], "udpPortRanges": [13, 13], "domainNames": ["abc.test.com", "xyz.test.com"], "segmentGroupId": "288261188247093285", "segmentGroupName": "", "serverGroups": [{"id": "CORP-WEST-1"}]}'
reply: 'HTTP/1.1 400 Bad Request\r\n'

DEBUG:urllib3.connectionpool:https://config.private.zscaler.com:443 "POST /mgmtconfig/v1/admin/customers/288261188247093248/application HTTP/1.1" 400 None
b'{\n  "id" : "invalid.resource.argument",\n  "reason" : "One or more input fields serverGroups are not valid."\n}'

- [] works
- [{"id":"CORP-WEST-1"}]  returns 400
- [{"id":"CORP-WEST-1"}, {"id":"CORP-EAST-1"}] returns 400

For example

   testGroup= [{"id": "CORP-WEST-1"}]
    result = client.add_application_segment(
        name=data["shortName"],
        healthReporting="NONE",
        domainNames=fqdns,
        segmentGroupId=group_id,
        serverGroups=testGroup,
        tcpPortRanges=zscaler_tcp_ports,
        udpPortRanges=zscaler_udp_ports,
    )

**Comment by zetan503** [comment]
I resolved this. need to pass the serverGroup id, not the name.

 [{'id': '288261188247093297'}, {'id': '288261188247093298'}]

**Comment by sergitopereira** [comment]
@zetan503 that is correct. You need the actual ID and no the name
Regards
Sergio
