### ISSUE TITLE
Paging of list_segment_group

### ISSUE THREAD

**Issue by zetan503** [sergitopereira/zscaler_api_talkers#46]
Noticed most functions page through the result set with this method
 response = self._obtain_all_results(url)

However list_segment_group() returns with a list

{"totalPages": "1", "totalCount": "5", "list": [{"id": "288261188247093422", etc ....

Should you implement _obtain_all_results in list_segment_groups?

**Comment by sergitopereira** [comment]
@zetan503  Thank you for your feedback.
As per ZPA Ranges and Limitations, a Tenant can contain up to Segment Groups  200 groups and the pagesize was 500 by default.  I have refactored this method and will be released in the upcoming next version. For now you can do a git pull to obtain this change along with really good to zia_talker.
Thanks

**Comment by sergitopereira** [comment]
@zetan503 https://github.com/sergitopereira/zscaler_api_talkers/commit/0a32088f4982be78d0050f6880616dab48abc1bf
Done.
