### ISSUE TITLE
Feature request: update app connector 

### ISSUE THREAD

**Issue by zetan503** [sergitopereira/zscaler_api_talkers#93]
Please implement update app connector
/mgmtconfig/v1/admin/customers/{customerId}/connector/{connectorId}
PUT Updates the App Connector details for the specified ID.

So that I can enable or disable an app connector ( or any field ) with an API call.

**Comment by sergitopereira** [comment]
@zetan503  I have added the required method. Please make sure to download latest release in a separate python virtual environment https://pypi.org/project/zscaler-api-talkers/
